import { nuevaTarea } from './tasks.ts'
import type { Estrategia, Tarea, Operacion, ConfigBombero } from './tasks.ts'
export function configuracionInicial(): Record<number, ConfigBombero> {
  return Object.fromEntries(Array.from({ length: 8 }, (_, i) => [i + 1, { nombre: `B${i + 1}`, velocidad: 4 }]))
}
export function secuenciaCompleta(): Estrategia {
  const tareas: Tarea[] = []
  const add = (id: string, operacion: Operacion, bombero: number, objetivo: string, dependencias: string[] = [], ayudantes: number[] = [], receptores: number[] = [], nombre?: string) => {
    tareas.push({ ...nuevaTarea(operacion, bombero, id), objetivo, dependencias, ayudantes, receptores, ...(nombre ? { nombre } : {}) })
  }
  for (const b of [1, 2, 3]) add(`entrada-${b}`, 'mover', b, 'muro-i')
  for (const b of [4, 5, 8]) add(`entrada-${b}`, 'mover', b, 'muro-iv')
  for (const b of [6, 7]) add(`entrada-${b}`, 'mover', b, 'tubo-iii')
  add('herramientas', 'recogerHerramientas', 1, 'herramientas')
  add('herramientas-muro', 'entregarHerramientas', 1, 'muro-iv', [], [], [8], 'B1 entrega herramientas a B8 por el muro')
  add('herramientas-tubo', 'entregarHerramientas', 8, 'tubo-iii', [], [], [6, 7], 'B8 pasa herramientas a B6 y B7 por el tubo')
  add('cruce-8', 'mover', 8, 'tubo-iii')
  add('puerta', 'abrirPuerta', 6, 'puerta', [], [7])
  add('linea', 'conectarLinea', 2, 'gemelo')
  add('agua', 'operarGemelo', 2, 'gemelo')
  add('piton-i', 'asignarPiton', 3, 'muro-i')
  add('apoyo-1', 'apoyarManguera', 1, 'blanco-1', ['agua'])
  add('blanco-1', 'derribar', 3, 'blanco-1', ['apoyo-1'])
  add('apoyo-2', 'apoyarManguera', 1, 'blanco-2', ['blanco-1'])
  add('blanco-2', 'derribar', 3, 'blanco-2', ['apoyo-2'])
  add('cerrar-i', 'cerrarPiton', 3, 'material')
  add('piton-iv', 'entregarPiton', 3, 'muro-iv', [], [], [4], 'B3 entrega el pitón cerrado a B4')
  add('piton-iii', 'asignarPiton', 8, 'tubo-iii')
  for (let n = 3; n <= 6; n++) add(`blanco-${n}`, 'derribar', 8, `blanco-${n}`, [`blanco-${n - 1}`, 'puerta'])
  add('cerrar-iii', 'cerrarPiton', 8, 'material')
  add('espera-tubo-8', 'mover', 8, 'tubo-iii')
  add('obtener-camilla', 'recogerCamilla', 7, 'camilla')
  add('camilla-tubo', 'entregarCamilla', 7, 'tubo-iv', [], [], [4, 5], 'B7 entrega camilla vacía a B4 y B5')
  add('camilla-muro', 'entregarCamilla', 4, 'muro-i', [], [5], [1, 3], 'B4 y B5 entregan camilla a B1 y B3')
  add('blanco-7', 'derribar', 4, 'blanco-7', ['blanco-6'])
  add('blanco-8', 'derribar', 4, 'blanco-8')
  add('cerrar-iv', 'cerrarPiton', 4, 'material')
  add('cargar', 'cargarVictima', 1, 'victima', [], [3])
  add('asegurar', 'asegurarVictima', 1, 'victima', [], [3])
  add('victima-muro', 'transportarVictima', 1, 'muro-i', [], [3])
  add('sostener-muro', 'sostenerCamilla', 3, 'camilla', ['victima-muro'], [], [], 'B3 sostiene la camilla mientras B1 cruza')
  add('salir-i-1', 'mover', 1, 'muro-iv', ['sostener-muro'])
  add('victima-entrega-muro', 'entregarVictima', 3, 'muro-iv', ['blanco-8', 'salir-i-1'], [], [1, 4, 5], 'B3 entrega víctima a B1, B4 y B5')
  add('salir-i-3', 'mover', 3, 'muro-iv')
  add('victima-tubo', 'transportarVictima', 1, 'tubo-iv', [], [3, 4, 5])
  add('sostener-tubo', 'sostenerCamilla', 1, 'camilla', [], [3, 4], [], 'B1, B3 y B4 sostienen; B5 se separa')
  add('subir', 'subirEscala', 5, 'banderin', ['victima-tubo'])
  add('banderin', 'retirarBanderin', 5, 'banderin')
  add('bajar', 'bajarEscala', 5, 'escala')
  add('espera-tubo-6', 'mover', 6, 'tubo-iii')
  add('victima-entrega-tubo', 'entregarVictima', 1, 'tubo-iii', [], [3, 4], [6, 7, 8], 'Relevo de víctima a B6, B7 y B8 por el tubo')
  add('cruce-1', 'mover', 1, 'tubo-iii')
  add('cruce-3', 'mover', 3, 'tubo-iii')
  add('cruce-4', 'mover', 4, 'tubo-iii')
  add('espera-gemelo', 'esperarBlanco', 2, 'blanco-8')
  add('salir-i-2', 'mover', 2, 'muro-iv', ['salir-i-3'])
  add('cruce-2', 'mover', 2, 'tubo-iii')
  for (const b of [2, 3, 4]) add(`puerta-${b}`, 'mover', b, 'puerta-ii')
  add('victima-meta', 'transportarVictima', 6, 'salida', ['cruce-1'], [1, 7, 8], [], 'B1, B6, B7 y B8 evacuan la víctima')
  for (let b = 1; b <= 8; b++) add(`meta-${b}`, 'salir', b, 'salida', ['victima-meta'])
  return { id: 'secuencia-completa', nombre: 'Secuencia completa B1–B8', tareas, bomberos: configuracionInicial() }
}
export function zonaIBase(): Estrategia {
  const tareas: Tarea[] = []
  const add = (id: string, operacion: Operacion, bombero: number | null, objetivo: string, dependencias: string[] = [], ayudantes: number[] = [], nombre?: string) => {
    tareas.push({ ...nuevaTarea(operacion, bombero, id), objetivo, dependencias, ayudantes, ...(nombre ? { nombre } : {}) })
  }
  add('piton-i', 'asignarPiton', 3, 'material')
  add('entrada-1', 'mover', 1, 'muro-i')
  add('entrada-2', 'mover', 2, 'muro-i')
  add('entrada-3', 'mover', 3, 'muro-i', ['piton-i'])
  add('herramientas', 'recogerHerramientas', 1, 'herramientas')
  add('entrega-herramientas', 'entregarHerramientas', 1, 'muro-iv')
  add('linea', 'conectarLinea', 2, 'gemelo')
  add('agua', 'operarGemelo', 2, 'gemelo', ['linea'])
  add('apoyo-1', 'apoyarManguera', 1, 'blanco-1', ['linea'])
  add('blanco-1', 'derribar', 3, 'blanco-1', ['agua', 'apoyo-1'])
  add('apoyo-2', 'apoyarManguera', 1, 'blanco-2', ['blanco-1'])
  add('blanco-2', 'derribar', 3, 'blanco-2', ['apoyo-2'])
  add('cerrar-i', 'cerrarPiton', 3, 'material', ['blanco-2'])
  add('recibir-herramientas', 'recogerHerramientas', null, 'herramientas', ['entrega-herramientas'], [], 'Equipo IV: recibir herramientas')
  add('puerta', 'abrirPuerta', null, 'puerta', ['recibir-herramientas'])
  add('obtener-camilla', 'recogerCamilla', null, 'camilla', ['puerta'])
  add('camilla-i', 'entregarCamilla', null, 'muro-i', ['obtener-camilla'])
  add('recibir-camilla', 'recogerCamilla', 1, 'camilla', ['camilla-i', 'cerrar-i'], [3])
  add('cargar', 'cargarVictima', 1, 'victima', [], [3])
  add('asegurar', 'asegurarVictima', 1, 'victima', [], [3])
  add('victima-muro', 'transportarVictima', 1, 'muro-i', [], [3])
  add('piton-externo', 'asignarPiton', null, 'material', [], [], 'Equipo externo: preparar segundo pitón')
  for (let i = 3; i <= 8; i++) add(`blanco-${i}`, 'derribar', null, `blanco-${i}`, [`blanco-${i - 1}`, 'piton-externo', 'puerta'])
  add('cerrar-externo', 'cerrarPiton', null, 'material', ['blanco-8'])
  add('entrega-victima', 'entregarVictima', 1, 'muro-iv', ['blanco-8'], [3])
  add('salir-i-1', 'mover', 1, 'muro-iv')
  add('salir-i-3', 'mover', 3, 'muro-iv', ['entrega-victima'])
  add('espera-gemelo', 'esperarBlanco', 2, 'blanco-8')
  add('salir-i-2', 'mover', 2, 'muro-iv', ['salir-i-1', 'salir-i-3'])
  add('tubo-2', 'mover', 2, 'tubo-iii')
  add('recibir-victima', 'recogerCamilla', null, 'camilla', ['entrega-victima'], [], 'Equipo IV: recibir víctima (asignar ayudante)')
  add('victima-meta', 'transportarVictima', null, 'salida', ['recibir-victima'], [], 'Equipo IV: víctima a meta (asignar ayudante)')
  add('subir', 'subirEscala', null, 'banderin', ['blanco-8'])
  add('banderin', 'retirarBanderin', null, 'banderin', ['subir'])
  add('bajar', 'bajarEscala', null, 'escala', ['banderin'])
  for (let i = 1; i <= 8; i++) add(`meta-${i}`, 'salir', i, 'salida', ['victima-meta', 'bajar', 'cerrar-externo'])
  return { id: 'zona-i-base', nombre: 'Zona I base', tareas, bomberos: configuracionInicial() }
}
